<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.3.1" />
    <PackageVersion Include="Enums.NET" Version="4.0.1" />
    <PackageVersion Include="ExtendedNumerics.BigDecimal" Version="2025.1001.2.129" />
    <PackageVersion Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.0" />
    <PackageVersion Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageVersion Include="NPOI" Version="2.7.3" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="SixLabors.Fonts" Version="1.0.1" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="2.1.10" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
    <PackageVersion Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageVersion Include="System.DirectoryServices" Version="9.0.5" />
    <PackageVersion Include="System.Management" Version="9.0.5" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="9.0.5" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="9.0.5" />
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="9.0.5" />
  </ItemGroup>
</Project>